-- MySQL Script generated by MySQL Workbench
-- Thu Nov 17 10:29:32 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Ecommerce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Ecommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Ecommerce` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `Ecommerce` ;

-- -----------------------------------------------------
-- Table `Ecommerce`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ecommerce`.`Categories` (
  `category_id` INT NOT NULL,
  `category_name` VARCHAR(60) NULL DEFAULT NULL,
  `category_description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Ecommerce`.`Option_Groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ecommerce`.`Option_Groups` (
  `Option_group_id` INT NOT NULL,
  `Option_group_name` VARCHAR(60) NULL DEFAULT NULL,
  PRIMARY KEY (`Option_group_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Ecommerce`.`Option_Values`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ecommerce`.`Option_Values` (
  `option_value_id` INT NOT NULL,
  `value_name` VARCHAR(60) NULL DEFAULT NULL,
  PRIMARY KEY (`option_value_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Ecommerce`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ecommerce`.`Users` (
  `user_id` INT NOT NULL,
  `user_role` VARCHAR(60) NULL DEFAULT NULL,
  `user_name` VARCHAR(60) NULL DEFAULT NULL,
  `user_email` VARCHAR(60) NULL DEFAULT NULL,
  `user_password` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Ecommerce`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ecommerce`.`Orders` (
  `order_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `user_name` VARCHAR(60) NULL DEFAULT NULL,
  `user_email` VARCHAR(60) NULL DEFAULT NULL,
  PRIMARY KEY (`order_id`, `user_id`),
  INDEX `fk_Orders` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Orders`
    FOREIGN KEY (`user_id`)
    REFERENCES `Ecommerce`.`Users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Ecommerce`.`Order_History`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ecommerce`.`Order_History` (
  `order_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `history_time` DATETIME NOT NULL,
  `history_status` VARCHAR(60) NULL DEFAULT NULL,
  `history_notes` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`order_id`, `history_time`, `user_id`),
  INDEX `fk_Order_History_Users` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Order_History_Orders`
    FOREIGN KEY (`order_id`)
    REFERENCES `Ecommerce`.`Orders` (`order_id`),
  CONSTRAINT `fk_Order_History_Users`
    FOREIGN KEY (`user_id`)
    REFERENCES `Ecommerce`.`Users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Ecommerce`.`Order_Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ecommerce`.`Order_Products` (
  `item_id` INT NOT NULL,
  `order_id` INT NOT NULL,
  `item_name` VARCHAR(60) NULL DEFAULT NULL,
  `item_price` DECIMAL(10,0) NULL DEFAULT NULL,
  `item_quantity` INT NULL DEFAULT NULL,
  PRIMARY KEY (`item_id`, `order_id`),
  INDEX `fk_Order_Products` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_Order_Products`
    FOREIGN KEY (`order_id`)
    REFERENCES `Ecommerce`.`Orders` (`order_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Ecommerce`.`Order_Product_Options`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ecommerce`.`Order_Product_Options` (
  `item_option_id` INT NOT NULL,
  `item_id` INT NOT NULL,
  `option_group` VARCHAR(60) NULL DEFAULT NULL,
  `option_value` VARCHAR(60) NULL DEFAULT NULL,
  PRIMARY KEY (`item_option_id`, `item_id`),
  INDEX `fk_Order_Product_Options` (`item_id` ASC) VISIBLE,
  CONSTRAINT `fk_Order_Product_Options`
    FOREIGN KEY (`item_id`)
    REFERENCES `Ecommerce`.`Order_Products` (`item_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Ecommerce`.`Order_Totals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ecommerce`.`Order_Totals` (
  `total_id` INT NOT NULL,
  `order_id` INT NOT NULL,
  `total_name` VARCHAR(60) NULL DEFAULT NULL,
  `total_amount` DECIMAL(10,0) NULL DEFAULT NULL,
  PRIMARY KEY (`total_id`, `order_id`),
  INDEX `fk_Order_Totals` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_Order_Totals`
    FOREIGN KEY (`order_id`)
    REFERENCES `Ecommerce`.`Orders` (`order_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Ecommerce`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ecommerce`.`Products` (
  `product_id` INT NOT NULL,
  `product_name` VARCHAR(255) NULL DEFAULT NULL,
  `product_description` VARCHAR(255) NULL DEFAULT NULL,
  `product_price` DECIMAL(10,0) NULL DEFAULT NULL,
  `product_status` VARCHAR(25) NULL DEFAULT NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Ecommerce`.`Product_Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ecommerce`.`Product_Categories` (
  `product_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`product_id`, `category_id`),
  INDEX `fk_Product_Categories_Categories` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_Product_Categories_Categories`
    FOREIGN KEY (`category_id`)
    REFERENCES `Ecommerce`.`Categories` (`category_id`),
  CONSTRAINT `fk_Product_Categories_Products`
    FOREIGN KEY (`product_id`)
    REFERENCES `Ecommerce`.`Products` (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Ecommerce`.`Product_Values`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ecommerce`.`Product_Values` (
  `product_id` INT NOT NULL,
  `option_group_id` INT NOT NULL,
  `option_value_id` INT NOT NULL,
  PRIMARY KEY (`product_id`, `option_group_id`, `option_value_id`),
  INDEX `FK_Product_Values_Option_Groups` (`option_group_id` ASC) VISIBLE,
  INDEX `FK_Product_Values_Option_Values` (`option_value_id` ASC) VISIBLE,
  CONSTRAINT `FK_Product_Values_Option_Groups`
    FOREIGN KEY (`option_group_id`)
    REFERENCES `Ecommerce`.`Option_Groups` (`Option_group_id`),
  CONSTRAINT `FK_Product_Values_Option_Values`
    FOREIGN KEY (`option_value_id`)
    REFERENCES `Ecommerce`.`Option_Values` (`option_value_id`),
  CONSTRAINT `FK_Product_Values_Products`
    FOREIGN KEY (`product_id`)
    REFERENCES `Ecommerce`.`Products` (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Ecommerce`.`Product_options`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ecommerce`.`Product_options` (
  `product_id` INT NOT NULL,
  `option_group_id` INT NOT NULL,
  `option_group_type` VARCHAR(60) NULL DEFAULT NULL,
  PRIMARY KEY (`product_id`, `option_group_id`),
  INDEX `FK_Product_options_Option_Groups` (`option_group_id` ASC) VISIBLE,
  CONSTRAINT `FK_Product_options_Option_Groups`
    FOREIGN KEY (`option_group_id`)
    REFERENCES `Ecommerce`.`Option_Groups` (`Option_group_id`),
  CONSTRAINT `FK_Product_options_Products`
    FOREIGN KEY (`product_id`)
    REFERENCES `Ecommerce`.`Products` (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Ecommerce`.`Shopping_Cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ecommerce`.`Shopping_Cart` (
  `product_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `product_option` VARCHAR(45) NULL DEFAULT NULL,
  `quantity` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`product_id`, `user_id`),
  INDEX `FK_Shopping_Cart_Users` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK_Shopping_Cart_Product_Options`
    FOREIGN KEY (`product_id`)
    REFERENCES `Ecommerce`.`Product_options` (`product_id`),
  CONSTRAINT `FK_Shopping_Cart_Product_Values`
    FOREIGN KEY (`product_id`)
    REFERENCES `Ecommerce`.`Product_Values` (`product_id`),
  CONSTRAINT `FK_Shopping_Cart_Products`
    FOREIGN KEY (`product_id`)
    REFERENCES `Ecommerce`.`Products` (`product_id`),
  CONSTRAINT `FK_Shopping_Cart_Users`
    FOREIGN KEY (`user_id`)
    REFERENCES `Ecommerce`.`Users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
